version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend/data:/app/data 
    restart: always

  frontend:
      build: ./frontend
      container_name: project-frontend-1
      ports:
        - "5173:5173"
      stdin_open: true
      tty: true
      environment:
        - VITE_PORT=5173
      command: npm start
