version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend/data:/app/data 
    restart: always

  frontend:
      build: ./frontend
      container_name: project-frontend-1
      ports:
        - "3000:3000"
      stdin_open: true
      tty: true
      command: npm start
